// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIVsiNlIEVO7hQTVT4NA_9I2ESjKx6Xg',
    appId: '1:974012134672:web:ba9de1834784b01e7ae195',
    messagingSenderId: '974012134672',
    projectId: 'metature-3d682',
    authDomain: 'metature-3d682.firebaseapp.com',
    storageBucket: 'metature-3d682.appspot.com',
    measurementId: 'G-KFYX09HDRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZskIvYmwgJ_LgrcUOTpGwHwxgCMrFd8',
    appId: '1:974012134672:android:779c8324bf45b2627ae195',
    messagingSenderId: '974012134672',
    projectId: 'metature-3d682',
    storageBucket: 'metature-3d682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSex6-w_JxI1bzrZHEc9Xl_j1Q9QYLfc',
    appId: '1:974012134672:ios:4525d066f60df99d7ae195',
    messagingSenderId: '974012134672',
    projectId: 'metature-3d682',
    storageBucket: 'metature-3d682.appspot.com',
    iosClientId: '974012134672-too7mongug90992qjn74l8tblbfb4gap.apps.googleusercontent.com',
    iosBundleId: 'com.metature.metature2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPSex6-w_JxI1bzrZHEc9Xl_j1Q9QYLfc',
    appId: '1:974012134672:ios:4525d066f60df99d7ae195',
    messagingSenderId: '974012134672',
    projectId: 'metature-3d682',
    storageBucket: 'metature-3d682.appspot.com',
    iosClientId: '974012134672-too7mongug90992qjn74l8tblbfb4gap.apps.googleusercontent.com',
    iosBundleId: 'com.metature.metature2',
  );
}
